/**
 * Pins the backend POINTS ladder to the canonical `scoring-points.json`
 * (generated by tools/generate-aircraft-types.py, also bundled + pinned by the
 * iOS `ScoringPointsParityTests`). Because both platforms assert against the
 * same file, editing one side's literal without the other fails CI — the
 * profile-vs-leaderboard drift class can't recur.
 */
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  pointsForRarity,
  UNKNOWN_RARITY_POINTS,
  type Rarity,
} from "../src/catches/points.js";

const here = dirname(fileURLToPath(import.meta.url));
const canonicalPath = resolve(
  here,
  "../../ios/Tailspot/Tailspot/scoring-points.json",
);
const canonical = JSON.parse(readFileSync(canonicalPath, "utf8")) as Record<
  Rarity,
  number
>;
const tiers: Rarity[] = ["common", "uncommon", "rare", "epic", "legendary"];

describe("scoring points parity (backend ↔ canonical scoring-points.json)", () => {
  it("every backend tier matches the canonical file", () => {
    for (const tier of tiers) {
      expect(pointsForRarity(tier)).toBe(canonical[tier]);
    }
  });

  it("the canonical file defines exactly the five tiers", () => {
    expect(Object.keys(canonical).sort()).toEqual([...tiers].sort());
  });

  it("the unknown floor equals the common tier", () => {
    expect(UNKNOWN_RARITY_POINTS).toBe(canonical.common);
  });
});
