/**
 * Pins the backend POINTS ladder to the canonical `scoring-points.json` and the
 * bonus FRACTIONS to the canonical `scoring-bonuses.json` (both generated by
 * tools/generate-aircraft-types.py, also bundled + pinned by the iOS parity
 * tests). Because both platforms assert against the same files, editing one
 * side's literal without the other fails CI — the profile-vs-leaderboard drift
 * class can't recur, and the guess percentages can't grow the same drift class
 * the ladder escaped.
 */
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  FIRST_OF_TYPE_BONUS_FRACTION,
  GUESS_BONUS_FRACTIONS,
  type Rarity,
  UNKNOWN_RARITY_POINTS,
  firstOfTypeBonus,
  guessBonus,
  pointsForRarity,
} from "../src/catches/points.js";

const here = dirname(fileURLToPath(import.meta.url));
const canonicalPath = resolve(here, "../../ios/Tailspot/Tailspot/scoring-points.json");
const canonical = JSON.parse(readFileSync(canonicalPath, "utf8")) as Record<Rarity, number>;
const bonusesPath = resolve(here, "../../ios/Tailspot/Tailspot/scoring-bonuses.json");
const bonuses = JSON.parse(readFileSync(bonusesPath, "utf8")) as {
  firstOfType: number;
  routeGuess: number;
  typeGuess: number;
};
const tiers: Rarity[] = ["common", "uncommon", "rare", "epic", "legendary"];

describe("scoring points parity (backend ↔ canonical scoring-points.json)", () => {
  it("every backend tier matches the canonical file", () => {
    for (const tier of tiers) {
      expect(pointsForRarity(tier)).toBe(canonical[tier]);
    }
  });

  it("the canonical file defines exactly the five tiers", () => {
    expect(Object.keys(canonical).sort()).toEqual([...tiers].sort());
  });

  it("the unknown floor equals the common tier", () => {
    expect(UNKNOWN_RARITY_POINTS).toBe(canonical.common);
  });
});

describe("bonus parity (backend ↔ canonical scoring-bonuses.json)", () => {
  it("the canonical file defines exactly the three bonus fractions", () => {
    expect(Object.keys(bonuses).sort()).toEqual(["firstOfType", "routeGuess", "typeGuess"]);
  });

  it("every backend fraction matches the canonical file", () => {
    expect(FIRST_OF_TYPE_BONUS_FRACTION).toBe(bonuses.firstOfType);
    expect(GUESS_BONUS_FRACTIONS.route).toBe(bonuses.routeGuess);
    expect(GUESS_BONUS_FRACTIONS.type).toBe(bonuses.typeGuess);
  });

  it("the bonus helpers apply the canonical fractions (rounded) to every base tier", () => {
    for (const tier of tiers) {
      const base = pointsForRarity(tier);
      expect(firstOfTypeBonus(base)).toBe(Math.round(base * bonuses.firstOfType));
      expect(guessBonus(base, "route")).toBe(Math.round(base * bonuses.routeGuess));
      expect(guessBonus(base, "type")).toBe(Math.round(base * bonuses.typeGuess));
    }
  });
});
