//
//  AircraftNaming.swift
//  Tailspot
//
//  Canonical aircraft names. OpenSky's metadata DB carries raw,
//  inconsistent strings — "BOEING" / "737-8H4" (the H4 is a Boeing
//  CUSTOMER code: it encodes the airline, not the model — Southwest
//  in this case). We resolve to official names at READ time; the raw
//  strings stay stored on Catch untouched, so rule improvements are
//  retroactive and nothing needs a migration.
//
//  Resolution order:
//   1. ICAO type designator (B738, B77W…) against the bundled DOC 8643
//      table (AircraftTypes.json, generated by
//      tools/generate-aircraft-types.py — full ~2,600-designator set).
//   2. String cleanup fallback for rows without a typecode: Boeing
//      customer-code collapse, make title-casing, make/model dedupe.
//
//  `nonisolated` per repo convention: pure value logic that must be
//  callable from any actor.
//

import Foundation

nonisolated enum AircraftNaming {

    /// Resolved official (or best-effort cleaned) name, plus the
    /// authoritative aircraft type derived from DOC 8643 classification
    /// data (description, engine type, wake turbulence category).
    struct CanonicalName: Equatable, Sendable {
        let make: String?
        let model: String?
        /// DOC 8643-derived aircraft type. nil for entries from older
        /// JSON without the field (safe: callers fall through to the
        /// string classifier when nil).
        let type: AircraftType?

        init(make: String?, model: String?, type: AircraftType? = nil) {
            self.make = make
            self.model = model
            self.type = type
        }

        /// "Boeing 777-300ER" — the string display surfaces show and
        /// the Hangar groups by. nil only when both halves are nil.
        var displayName: String? {
            switch (make, model) {
            case let (m?, d?): return "\(m) \(d)"
            case let (m?, nil): return m
            case let (nil, d?): return d
            case (nil, nil): return nil
            }
        }
    }

    // MARK: - Entry points

    static func canonical(
        typecode: String?,
        manufacturer: String?,
        model: String?
    ) -> CanonicalName {
        if let code = typecode?.trimmingCharacters(in: .whitespacesAndNewlines)
            .uppercased().nonEmpty,
           let hit = table[code] {
            return hit
        }
        let make = cleanedMake(manufacturer)
        return CanonicalName(make: make, model: cleanedModel(model, make: make))
    }

    /// AircraftType for an ICAO typecode from the bundled table, nil if
    /// unknown. Authoritative classification source — preferred over the
    /// string classifier whenever a typecode is known.
    static func aircraftType(forTypecode typecode: String?) -> AircraftType? {
        guard let code = typecode?.trimmingCharacters(in: .whitespacesAndNewlines)
            .uppercased().nonEmpty else { return nil }
        return table[code]?.type
    }

    // MARK: - Bundled DOC 8643 table

    /// designator → canonical name + type. Decoded once on first touch.
    /// Missing/corrupt resource degrades to an empty table — every
    /// lookup falls through to the string path; never crashes.
    static let table: [String: CanonicalName] = {
        guard let url = Bundle.main.url(forResource: "AircraftTypes", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let raw = try? JSONDecoder().decode([String: Entry].self, from: data)
        else { return [:] }
        return raw.mapValues {
            CanonicalName(
                make: $0.make,
                model: $0.model,
                type: $0.type.flatMap { AircraftType(rawValue: $0) }
            )
        }
    }()

    private struct Entry: Decodable {
        let make: String
        let model: String
        /// DOC 8643-derived type string. Optional for back-compat with
        /// JSON entries regenerated before this field was added.
        let type: String?
    }

    // MARK: - Fallback: make

    /// Deliberately-capitalized makes (acronyms). Mirrors the
    /// generator's SPECIAL_MAKES; only matters for the string path.
    private static let makeExceptions: Set<String> = ["ATR", "PZL", "CASA", "MBB", "NAMC"]
    private static let makeSpecials: [String: String] = [
        "MCDONNELL DOUGLAS": "McDonnell Douglas",
        "DE HAVILLAND": "De Havilland",
        "DE HAVILLAND CANADA": "De Havilland Canada",
        "SAAB": "Saab",
        "BAE SYSTEMS": "BAE Systems",
    ]

    static func cleanedMake(_ raw: String?) -> String? {
        guard let trimmed = raw?.trimmingCharacters(in: .whitespacesAndNewlines).nonEmpty
        else { return nil }
        let collapsed = trimmed.split(separator: " ").joined(separator: " ")
        let upper = collapsed.uppercased()
        if let special = makeSpecials[upper] { return special }
        // Already mixed-case → trust the source.
        guard collapsed == upper else { return collapsed }
        return collapsed.split(separator: " ")
            .map { word in
                let w = String(word)
                return makeExceptions.contains(w) ? w : w.capitalized
            }
            .joined(separator: " ")
    }

    // MARK: - Fallback: model

    /// Boeing customer-code shape: optional leading "B", 7x7 family,
    /// dash, variant digit, 2-char customer code, optional
    /// (possibly parenthesised) suffix. "737-8H4" → 737-800;
    /// "777-322" → 777-300 (all-digit codes exist — 22 is United);
    /// "767-332(ER)" → 767-300ER. Idempotent on clean strings by
    /// construction: "737-800" parses as variant 8 + code "00" and
    /// rebuilds identically. Extended `#/…/#` delimiters so the
    /// literal doesn't depend on the bare-slash-regex feature flag.
    private static let customerCode =
        #/^B?(7[0-9]7)-([0-9])([A-Z0-9]{2})\(?([A-Z]{1,3})?\)?$/#

    /// Space-to-dash join, scoped ONLY to Airbus A3xx and Boeing 7x7
    /// families where the part after the space STARTS with a digit.
    /// "A380 842" → "A380-842", "777 300ER" → "777-300ER".
    /// "737 MAX 8" stays unchanged (MAX starts with a letter).
    /// A220-series (A2xx) is deliberately excluded.
    private static let spaceDashJoin =
        #/^(A3[0-9]{2}|7[0-9]7) ([0-9][A-Z0-9]*)$/#

    /// Airbus engine-variant collapse: raw suffix digits encode
    /// series/engine/version; the marketing name is series-hundred.
    ///   "A380-842" → variant 8 + engine code 42 → "A380-800"
    ///   "A321-271NX" → series 2 + neo → "A321neo"
    ///   "A330-243F"  → series 2 + freighter → "A330-200F"
    /// Pattern requires EXACTLY 3 variant digits (family-digit + 2)
    /// so "A350-1000" (4 digits) and "A330-900" (series-hundred already)
    /// fall through unchanged. Idempotent: "A380-800" → series 8 +
    /// code "00" + no suffix → "A380-800".
    private static let airbusVariant =
        #/^(A3[0-9]{2})-([0-9])([0-9]{2})(NX|N|F)?$/#

    /// Boeing 737 MAX short designation. Boeing names the MAX family
    /// "737-7/-8/-9/-10" (single digit), distinct from the previous-gen
    /// 737 NG which is always 3-digit ("737-700/-800/-900"). A bare
    /// "737-8" IS the MAX 8 (typecode B38M → "737 MAX 8"); without this
    /// rule a no-typecode MAX 8 fell out as "737-8" and fragmented into
    /// its own Set away from the typecode-resolved "737 MAX 8". "737-800"
    /// has three digits and is NOT matched — the NG stays its own type.
    private static let boeing737Max =
        #/^B?737-(7|8|9|10)$/#

    static func cleanedModel(_ raw: String?, make: String?) -> String? {
        guard let trimmed = raw?.trimmingCharacters(in: .whitespacesAndNewlines).nonEmpty
        else { return nil }
        var model = trimmed.split(separator: " ").joined(separator: " ")
        // Manufacturer repeated inside the model ("BOEING 737-800"
        // with make Boeing) reads twice once joined — drop it.
        if let make, model.lowercased().hasPrefix(make.lowercased() + " ") {
            // make.count is case-invariant for ASCII names; the prefix is
            // established via lowercased() but sliced on the original.
            model = String(model.dropFirst(make.count + 1))
        }
        // Boeing 737 MAX short code ("737-8" → "737 MAX 8"), so a
        // no-typecode MAX converges with the typecode table's name.
        // Must run BEFORE customer-code collapse (which would otherwise
        // leave the bare short code untouched). "737-800" is 3-digit
        // and falls through to NG handling below.
        if let m = model.uppercased().wholeMatch(of: boeing737Max) {
            model = "737 MAX \(m.1)"
        }
        // (a) Space-to-dash join for Airbus A3xx / Boeing 7x7 families
        // where the token after the space starts with a digit.
        else if let m = model.wholeMatch(of: spaceDashJoin) {
            model = "\(m.1)-\(m.2)"
        }
        // Boeing customer-code collapse.
        if let m = model.uppercased().wholeMatch(of: customerCode) {
            let suffix = m.4.map(String.init) ?? ""
            model = "\(m.1)-\(m.2)00\(suffix)"
        }
        // (b) Airbus engine-variant collapse (applied AFTER space-to-dash).
        if let m = model.wholeMatch(of: airbusVariant) {
            let family = String(m.1)
            let series = String(m.2)
            let suffix = m.4.map(String.init) ?? ""
            switch suffix {
            case "N", "NX":
                // neo variants: A321-271NX → A321neo
                model = "\(family)neo"
            case "F":
                // freighter: A330-243F → A330-200F
                model = "\(family)-\(series)00F"
            default:
                // standard: A380-842 → A380-800
                model = "\(family)-\(series)00"
            }
        }
        return model
    }
}

private nonisolated extension String {
    var nonEmpty: String? { isEmpty ? nil : self }
}
