//
//  AircraftNaming.swift
//  Tailspot
//
//  Canonical aircraft names. OpenSky's metadata DB carries raw,
//  inconsistent strings — "BOEING" / "737-8H4" (the H4 is a Boeing
//  CUSTOMER code: it encodes the airline, not the model — Southwest
//  in this case). We resolve to official names at READ time; the raw
//  strings stay stored on Catch untouched, so rule improvements are
//  retroactive and nothing needs a migration.
//
//  Resolution order:
//   1. ICAO type designator (B738, B77W…) against the bundled DOC 8643
//      table (AircraftTypes.json, generated by
//      tools/generate-aircraft-types.py — full ~2,600-designator set).
//   2. String cleanup fallback for rows without a typecode: Boeing
//      customer-code collapse, make title-casing, make/model dedupe.
//
//  `nonisolated` per repo convention: pure value logic that must be
//  callable from any actor.
//

import Foundation

nonisolated enum AircraftNaming {

    /// Resolved official (or best-effort cleaned) name.
    struct CanonicalName: Equatable, Sendable {
        let make: String?
        let model: String?

        /// "Boeing 777-300ER" — the string display surfaces show and
        /// the Hangar groups by. nil only when both halves are nil.
        var displayName: String? {
            switch (make, model) {
            case let (m?, d?): return "\(m) \(d)"
            case let (m?, nil): return m
            case let (nil, d?): return d
            case (nil, nil): return nil
            }
        }
    }

    // MARK: - Entry point

    static func canonical(
        typecode: String?,
        manufacturer: String?,
        model: String?
    ) -> CanonicalName {
        if let code = typecode?.trimmingCharacters(in: .whitespacesAndNewlines)
            .uppercased().nonEmpty,
           let hit = table[code] {
            return hit
        }
        let make = cleanedMake(manufacturer)
        return CanonicalName(make: make, model: cleanedModel(model, make: make))
    }

    // MARK: - Bundled DOC 8643 table

    /// designator → canonical name. Decoded once on first touch.
    /// Missing/corrupt resource degrades to an empty table — every
    /// lookup falls through to the string path; never crashes.
    static let table: [String: CanonicalName] = {
        guard let url = Bundle.main.url(forResource: "AircraftTypes", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let raw = try? JSONDecoder().decode([String: Entry].self, from: data)
        else { return [:] }
        return raw.mapValues { CanonicalName(make: $0.make, model: $0.model) }
    }()

    private struct Entry: Decodable {
        let make: String
        let model: String
    }

    // MARK: - Fallback: make

    /// Deliberately-capitalized makes (acronyms). Mirrors the
    /// generator's SPECIAL_MAKES; only matters for the string path.
    private static let makeExceptions: Set<String> = ["ATR", "PZL", "CASA", "MBB", "NAMC"]
    private static let makeSpecials: [String: String] = [
        "MCDONNELL DOUGLAS": "McDonnell Douglas",
        "DE HAVILLAND": "De Havilland",
        "DE HAVILLAND CANADA": "De Havilland Canada",
        "SAAB": "Saab",
        "BAE SYSTEMS": "BAE Systems",
    ]

    static func cleanedMake(_ raw: String?) -> String? {
        guard let trimmed = raw?.trimmingCharacters(in: .whitespacesAndNewlines).nonEmpty
        else { return nil }
        let collapsed = trimmed.split(separator: " ").joined(separator: " ")
        let upper = collapsed.uppercased()
        if let special = makeSpecials[upper] { return special }
        // Already mixed-case → trust the source.
        guard collapsed == upper else { return collapsed }
        return collapsed.split(separator: " ")
            .map { word in
                let w = String(word)
                return makeExceptions.contains(w) ? w : w.capitalized
            }
            .joined(separator: " ")
    }

    // MARK: - Fallback: model

    /// Boeing customer-code shape: optional leading "B", 7x7 family,
    /// dash, variant digit, 2-char customer code, optional
    /// (possibly parenthesised) suffix. "737-8H4" → 737-800;
    /// "777-322" → 777-300 (all-digit codes exist — 22 is United);
    /// "767-332(ER)" → 767-300ER. Idempotent on clean strings by
    /// construction: "737-800" parses as variant 8 + code "00" and
    /// rebuilds identically. Extended `#/…/#` delimiters so the
    /// literal doesn't depend on the bare-slash-regex feature flag.
    private static let customerCode =
        #/^B?(7[0-9]7)-([0-9])([A-Z0-9]{2})\(?([A-Z]{1,3})?\)?$/#

    static func cleanedModel(_ raw: String?, make: String?) -> String? {
        guard let trimmed = raw?.trimmingCharacters(in: .whitespacesAndNewlines).nonEmpty
        else { return nil }
        var model = trimmed.split(separator: " ").joined(separator: " ")
        // Manufacturer repeated inside the model ("BOEING 737-800"
        // with make Boeing) reads twice once joined — drop it.
        if let make, model.lowercased().hasPrefix(make.lowercased() + " ") {
            // make.count is case-invariant for ASCII names; the prefix is
            // established via lowercased() but sliced on the original.
            model = String(model.dropFirst(make.count + 1))
        }
        if let m = model.uppercased().wholeMatch(of: customerCode) {
            let suffix = m.4.map(String.init) ?? ""
            model = "\(m.1)-\(m.2)00\(suffix)"
        }
        return model
    }
}

private nonisolated extension String {
    var nonEmpty: String? { isEmpty ? nil : self }
}
