//
//  FAARegistry.swift
//  Tailspot
//
//  Offline US-aircraft identity from the bundled FAA Releasable
//  Aircraft Database (faa-aircraft.bin + faa-models.json, generated by
//  tools/generate-faa-registry.py). The fallback when OpenSky 404s.
//  US-only; a snapshot (regenerate to refresh).
//
import Foundation

nonisolated enum FAARegistry {
    struct Record: Equatable, Sendable {
        let make: String
        let model: String
        let type: AircraftType?   // decoded from the bundled raw value
    }

    /// Look up by icao24 (lowercase hex). nil if not a US-registered
    /// airframe in the bundled snapshot. Binary search over the sorted
    /// .bin; lazy one-time load.
    static func record(forIcao24 icao24: String) -> Record? {
        guard let v = UInt32(icao24.trimmingCharacters(in: .whitespaces), radix: 16) else { return nil }
        guard let store = store else { return nil }
        // binary search store.keys for v
        var lo = 0, hi = store.count - 1
        while lo <= hi {
            let mid = (lo + hi) / 2
            let k = store.icao(at: mid)
            if k == v {
                let idx = Int(store.modelIndex(at: mid))
                guard idx < store.models.count else { return nil }
                let t = store.models[idx]
                return Record(make: t.0, model: t.1, type: AircraftType(rawValue: t.2))
            } else if k < v { lo = mid + 1 } else { hi = mid - 1 }
        }
        return nil
    }

    // MARK: - Lazy bundled store
    private struct Store {
        let data: Data            // faa-aircraft.bin (6 bytes/record, sorted)
        let count: Int
        let models: [(String, String, String)]
        func icao(at i: Int) -> UInt32 {
            let o = i * 6
            return (UInt32(data[data.startIndex + o]) << 24)
                 | (UInt32(data[data.startIndex + o + 1]) << 16)
                 | (UInt32(data[data.startIndex + o + 2]) << 8)
                 |  UInt32(data[data.startIndex + o + 3])
        }
        func modelIndex(at i: Int) -> UInt16 {
            let o = i * 6 + 4
            return (UInt16(data[data.startIndex + o]) << 8) | UInt16(data[data.startIndex + o + 1])
        }
    }
    private static let store: Store? = {
        guard let binURL = Bundle.main.url(forResource: "faa-aircraft", withExtension: "bin"),
              let data = try? Data(contentsOf: binURL),
              data.count % 6 == 0,
              let jsonURL = Bundle.main.url(forResource: "faa-models", withExtension: "json"),
              let jsonData = try? Data(contentsOf: jsonURL),
              let raw = try? JSONDecoder().decode([[String]].self, from: jsonData)
        else { return nil }
        let models = raw.map { ($0[0], $0[1], $0.count > 2 ? $0[2] : "ga") }
        return Store(data: data, count: data.count / 6, models: models)
    }()
}
