/**
 * Aircraft type → name + Tailspot rarity tier.
 *
 * The tier ladder is the APP's own: we read the same AircraftTypes.json the
 * iOS app bundles (generated by tools/generate-aircraft-types.py), so a slide
 * that says "EPIC in Tailspot" matches what a user would see on catching it.
 * Never hand-assign a tier here.
 */

import { readFileSync } from "node:fs";
import { AIRCRAFT_TYPES_PATH } from "./paths.ts";

export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary";
export type TypeClass = "wide" | "narrow" | "regional" | "biz" | "ga" | "mil";

export interface TypeInfo {
  make: string;
  model: string;
  rarity: Rarity;
  type: TypeClass;
  lengthFt?: number;
  wingspanFt?: number;
}

export const RARITY_ORDER: readonly Rarity[] = ["common", "uncommon", "rare", "epic", "legendary"];

/** Mirrors backend/src/catches/points.ts (base points, no bonuses). */
export const RARITY_POINTS: Record<Rarity, number> = {
  common: 10,
  uncommon: 20,
  rare: 50,
  epic: 100,
  legendary: 500,
};

/** Mirrors the app's tier tints (GameSystem.swift `Rarity.tint`). */
export const RARITY_COLORS: Record<Rarity, string> = {
  common: "#8595A5",
  uncommon: "#4ECCA3",
  rare: "#00D4FF",
  epic: "#9B5DE5",
  legendary: "#FFC74A",
};

export function rarityRank(r: Rarity): number {
  return RARITY_ORDER.indexOf(r);
}

let cache: Record<string, TypeInfo> | null = null;

export function loadTypes(path = AIRCRAFT_TYPES_PATH): Record<string, TypeInfo> {
  if (!cache) cache = JSON.parse(readFileSync(path, "utf8")) as Record<string, TypeInfo>;
  return cache;
}

export function typeInfo(code: string | null | undefined): TypeInfo | null {
  if (!code) return null;
  return loadTypes()[code.toUpperCase()] ?? null;
}

/**
 * DOC 8643 model strings are sometimes a sub-variant or a foreign
 * designation ("C-16" for the Eurofighter, "F-16 Netz", "EC-130 Aya"). For a
 * headline we want the name an avgeek would say. Only cosmetic: the tier
 * still comes from the table.
 */
const DISPLAY_NAMES: Record<string, string> = {
  A388: "Airbus A380",
  B748: "Boeing 747-8",
  B744: "Boeing 747-400",
  B742: "Boeing 747-200",
  A124: "Antonov An-124 Ruslan",
  AN22: "Antonov An-22",
  IL76: "Ilyushin Il-76",
  MD11: "McDonnell Douglas MD-11",
  DC10: "McDonnell Douglas DC-10",
  L101: "Lockheed L-1011 TriStar",
  B52: "Boeing B-52 Stratofortress",
  B1: "Rockwell B-1 Lancer",
  B2: "Northrop B-2 Spirit",
  C17: "Boeing C-17 Globemaster III",
  C5M: "Lockheed C-5M Super Galaxy",
  C130: "Lockheed C-130 Hercules",
  C30J: "Lockheed C-130J Super Hercules",
  K35R: "Boeing KC-135 Stratotanker",
  K35E: "Boeing KC-135 Stratotanker",
  E3TF: "Boeing E-3 Sentry (AWACS)",
  E3CF: "Boeing E-3 Sentry (AWACS)",
  E6: "Boeing E-6 Mercury",
  P8: "Boeing P-8 Poseidon",
  A400: "Airbus A400M Atlas",
  EUFI: "Eurofighter Typhoon",
  F16: "F-16 Fighting Falcon",
  F35: "F-35 Lightning II",
  F15: "F-15 Eagle",
  F22: "F-22 Raptor",
  U2: "Lockheed U-2",
  V22: "Bell Boeing V-22 Osprey",
  H47: "Boeing CH-47 Chinook",
  H60: "Sikorsky H-60 Black Hawk",
  GLEX: "Bombardier Global Express",
  CL35: "Bombardier Challenger 350",
  CL60: "Bombardier Challenger 600",
  BLCF: "Boeing 747 Dreamlifter",
  A337: "Airbus Beluga XL",
  A3ST: "Airbus Beluga",
};

export function displayName(code: string): string {
  const c = code.toUpperCase();
  if (DISPLAY_NAMES[c]) return DISPLAY_NAMES[c];
  const t = typeInfo(c);
  if (!t) return c;
  // Avoid "Boeing Boeing …" style duplication when the model already names the maker.
  return t.model.toLowerCase().startsWith(t.make.toLowerCase()) ? t.model : `${t.make} ${t.model}`;
}

/** Short name for big type ("A380", "747-8", "C-17"). */
export function shortName(code: string): string {
  const full = displayName(code);
  const t = typeInfo(code);
  if (t && full.startsWith(t.make + " ")) return full.slice(t.make.length + 1);
  // Strip a leading maker word we added via DISPLAY_NAMES.
  return full.replace(/^(Airbus|Boeing|Antonov|Ilyushin|McDonnell Douglas|Lockheed|Rockwell|Northrop|Bell Boeing|Sikorsky|Eurofighter)\s+/, "") || full;
}

/** The compact designator for a big HUD label: "B-52", "A380", "747-8", "KC-135". */
export function designator(code: string): string {
  const s = shortName(code);
  const first = s.split(" ")[0];
  // "B-52 Stratofortress" → "B-52", "A400M Atlas" → "A400M"
  if (/\d/.test(first) && /[A-Za-z]/.test(first)) return first;
  // "747-8", "Typhoon", "Learjet 45"
  if (/^\d+$/.test(first)) {
    const full = displayName(code);
    if (full.length > 10) return first.length >= 3 ? first : code.toUpperCase();
    return full;
  }
  if (/^[\d-]+$/.test(first)) return first;
  return s.length <= 10 ? s : code.toUpperCase();
}

/**
 * One true, checkable line per headline type. Keep these boring-accurate:
 * the site's whole claim is that this is real, so no superlatives we can't
 * back up. A type without an entry gets a generic data-driven line instead.
 */
export const TYPE_FACTS: Record<string, string> = {
  A388: "The largest passenger jet ever built. Airbus ended production in 2021 after 251 deliveries.",
  B748: "The final 747 variant, 76.3 m long. The very last 747 ever built was delivered in January 2023.",
  B744: "The Queen of the Skies. Most passenger 747-400s are retired; the survivors mostly haul cargo.",
  B742: "A 1970s-generation 747. Only a handful are still flying anywhere in the world.",
  A124: "Built to carry what almost nothing else can: locomotives, satellites, power-plant turbines.",
  AN22: "The largest turboprop aircraft ever built. Very few remain in service.",
  IL76: "A Soviet-era four-engine freighter that first flew in 1971 and still works hard today.",
  MD11: "The last widebody trijet in service. Passenger flights ended in 2014; the survivors fly cargo.",
  DC10: "A 1970s trijet. The few still flying are freighters, tankers and firefighting jets.",
  L101: "Lockheed's only widebody airliner. Almost none are left in the air.",
  B52: "First flew in 1952 and is still in service more than 70 years later.",
  B1: "A supersonic swing-wing bomber. The wings sweep back for high-speed flight.",
  C17: "A strategic airlifter built to land heavy loads on short, rough runways.",
  C5M: "One of the largest military aircraft in the world. The whole nose hinges up to load cargo.",
  C30J: "The latest Hercules. The C-130 family has been in production since the 1950s.",
  C130: "The Hercules: in production since the 1950s, the longest continuous run of any military aircraft.",
  K35R: "A flying fuel station. KC-135s have refuelled other aircraft in mid-air since 1957.",
  K35E: "A flying fuel station. KC-135s have refuelled other aircraft in mid-air since 1957.",
  E3TF: "AWACS: the 9 m rotating dome on its back is a long-range radar.",
  E3CF: "AWACS: the 9 m rotating dome on its back is a long-range radar.",
  E6: "An airborne command and communications post, built on the Boeing 707 airframe.",
  P8: "A maritime patrol jet built on the 737, made to hunt submarines.",
  A400: "Europe's four-engine turboprop airlifter, with eight-bladed propellers.",
  V22: "A tiltrotor: it takes off like a helicopter and cruises like a plane.",
  H47: "A twin-rotor heavy-lift helicopter. The Chinook first flew in 1961.",
  T38: "The US Air Force's supersonic jet trainer, in service since 1961. NASA astronauts fly it too.",
  B753: "The longest single-aisle twinjet Boeing ever built. Only 55 were made.",
};
