//
//  ScoringPointsParityTests.swift
//  TailspotTests
//
//  Pins iOS `Rarity.basePoints` to the canonical `scoring-points.json` — the
//  single source generated by tools/generate-aircraft-types.py. The backend
//  has a matching parity test against the same file, so the two point ladders
//  cannot silently drift (the profile-vs-leaderboard bug class).
//

import Testing
import Foundation
@testable import Tailspot

@Suite("Scoring points — iOS ↔ canonical parity")
struct ScoringPointsParityTests {

    @Test func basePointsMatchCanonicalJSON() throws {
        let url = try #require(
            Bundle.main.url(forResource: "scoring-points", withExtension: "json"),
            "scoring-points.json must be bundled (generated next to AircraftTypes.json)"
        )
        let canonical = try JSONDecoder().decode(
            [String: Int].self, from: try Data(contentsOf: url)
        )

        // Every tier is present and every iOS literal matches the canonical file.
        #expect(canonical.count == Rarity.allCases.count)
        for r in Rarity.allCases {
            #expect(
                canonical[r.rawValue] == r.basePoints,
                "Rarity.\(r.rawValue).basePoints (\(r.basePoints)) != scoring-points.json (\(canonical[r.rawValue].map(String.init) ?? "missing"))"
            )
        }
    }
}
