/**
 * Rarity → points mapping (WP 1.5).
 *
 * Mirrors the canonical `scoring-points.json` (generated by
 * tools/generate-aircraft-types.py, bundled by iOS): common 10, uncommon 20,
 * rare 50, epic 100, legendary 500. `points.parity.test.ts` and the iOS
 * `ScoringPointsParityTests` both pin their literals to that file, so the two
 * ladders can't drift. An unknown/unresolved rarity scores the common floor
 * (10) — when the metadata service can't resolve a typecode, we still accept
 * the catch and award the baseline rather than rejecting it.
 *
 * Points are ALWAYS computed server-side from server-resolved rarity. The wire
 * contract carries no client points/rarity by design — never trust the client.
 */

export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

const POINTS: Record<Rarity, number> = {
  common: 10,
  uncommon: 20,
  rare: 50,
  epic: 100,
  legendary: 500,
};

/** The baseline awarded for an unknown/unresolved rarity. */
export const UNKNOWN_RARITY_POINTS = 10;

/**
 * The current scoring REGIME. Stamped onto every catch as `scoringVersion` so a
 * re-score can find rows scored under an older regime and re-derive them.
 *
 * BUMP THIS when the scoring LOGIC changes — the `POINTS` ladder below, the
 * `UNKNOWN_RARITY_POINTS` floor, or the icao24→typecode→rarity resolution chain
 * (`DrizzleCatchStore.resolveRarity`). After bumping, run `npm run rescore`
 * (see catches/rescore.ts) to bring every older-regime catch up to the new one.
 *
 * Do NOT bump for reference-DATA growth (the registry learning a new airframe):
 * those catches are still version-current, just resolved against better data —
 * `rescore` picks them up via their still-null `rarity`, not their version.
 */
export const CURRENT_SCORING_VERSION = 2;

/** Type guard for a known rarity tier string. */
export function isRarity(value: string | null | undefined): value is Rarity {
  return (
    value === "common" ||
    value === "uncommon" ||
    value === "rare" ||
    value === "epic" ||
    value === "legendary"
  );
}

/**
 * Points for a (possibly null / unknown) rarity string. Unresolved rarity →
 * UNKNOWN_RARITY_POINTS (10). Mirrors the iOS tiers exactly.
 */
export function pointsForRarity(rarity: string | null | undefined): number {
  return isRarity(rarity) ? POINTS[rarity] : UNKNOWN_RARITY_POINTS;
}

/**
 * The first-of-type BONUS for a given base: +50% of the base, rounded (R3, AE2).
 * A device's FIRST-ever catch of a typecode earns this on top of the base; a
 * later catch of the same type does not. Defined ONCE and used only by the
 * canonical scorer (`DrizzleCatchStore.scoreCatch`), so the upload path and the
 * re-score job add the same bonus and can't drift. The bonus floats with the
 * base — a first-of-type epic (100) earns 50, but if re-tiered to rare (50) it
 * earns 25.
 */
export function firstOfTypeBonus(base: number): number {
  return Math.round(base * 0.5);
}
