/**
 * Rarity → points mapping (WP 1.5).
 *
 * Mirrors the canonical `scoring-points.json` (generated by
 * tools/generate-aircraft-types.py, bundled by iOS): common 10, uncommon 20,
 * rare 50, epic 100, legendary 500. `points.parity.test.ts` and the iOS
 * `ScoringPointsParityTests` both pin their literals to that file, so the two
 * ladders can't drift. An unknown/unresolved rarity scores the common floor
 * (10) — when the metadata service can't resolve a typecode, we still accept
 * the catch and award the baseline rather than rejecting it.
 *
 * Points are ALWAYS computed server-side from server-resolved rarity. The wire
 * contract carries no client points/rarity by design — never trust the client.
 */

export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

const POINTS: Record<Rarity, number> = {
  common: 10,
  uncommon: 20,
  rare: 50,
  epic: 100,
  legendary: 500,
};

/** The baseline awarded for an unknown/unresolved rarity. */
export const UNKNOWN_RARITY_POINTS = 10;

/**
 * The current scoring REGIME. Stamped onto every catch as `scoringVersion` so a
 * re-score can find rows scored under an older regime and re-derive them.
 *
 * BUMP THIS when the scoring LOGIC changes — the `POINTS` ladder below, the
 * `UNKNOWN_RARITY_POINTS` floor, or the icao24→typecode→rarity resolution chain
 * (`DrizzleCatchStore.resolveRarity`). After bumping, run `npm run rescore`
 * (see catches/rescore.ts) to bring every older-regime catch up to the new one.
 *
 * Do NOT bump for reference-DATA growth (the registry learning a new airframe):
 * those catches are still version-current, just resolved against better data —
 * `rescore` picks them up via their still-null `rarity`, not their version.
 *
 * Version history:
 *   1 — launch regime (rarity ladder, unknown floor).
 *   2 — first-of-type +50% bonus.
 *   3 — server-verified guess bonuses (game-layer PR1, 2026-07-09): a correct
 *       pre-reveal guess adds +10% of base for "route", +25% for "type". The
 *       v2→v3 rescore is a PROVABLE ZERO-DELTA — no pre-v3 row has a guess
 *       recorded (guess_correct defaults false), so re-scoring only restamps
 *       versions. Run `npm run rescore -- --all --dry-run` and confirm Δ 0
 *       before applying; the bump still matters so the version history stays
 *       honest for the next real re-balance.
 */
export const CURRENT_SCORING_VERSION = 3;

/** Type guard for a known rarity tier string. */
function isRarity(value: string | null | undefined): value is Rarity {
  return (
    value === "common" ||
    value === "uncommon" ||
    value === "rare" ||
    value === "epic" ||
    value === "legendary"
  );
}

/**
 * Points for a (possibly null / unknown) rarity string. Unresolved rarity →
 * UNKNOWN_RARITY_POINTS (10). Mirrors the iOS tiers exactly.
 */
export function pointsForRarity(rarity: string | null | undefined): number {
  return isRarity(rarity) ? POINTS[rarity] : UNKNOWN_RARITY_POINTS;
}

/**
 * Bonus FRACTIONS — the single backend source, mirroring the canonical
 * `scoring-bonuses.json` (generated by tools/generate-aircraft-types.py next to
 * `scoring-points.json`; a SEPARATE file because shipped iOS clients pin
 * `scoring-points.json` as a strict {tier: points} map). `points.parity.test.ts`
 * pins these literals to that file so the fractions can't drift the way the
 * points ladder once did.
 */
export const FIRST_OF_TYPE_BONUS_FRACTION = 0.5;

/** The guessable question kinds of the pre-reveal bonus round (game-layer PR1). */
export type GuessKind = "route" | "type";

/** Type guard for a guess-kind string (the wire enum for `guess.kind`). */
export function isGuessKind(value: unknown): value is GuessKind {
  return value === "route" || value === "type";
}

/** Correct-guess bonus fractions: route is a near coin-flip (+10%); calling the
 *  exact type is the marquee skill test (+25%, still under first-of-type's +50%). */
export const GUESS_BONUS_FRACTIONS: Record<GuessKind, number> = {
  route: 0.1,
  type: 0.25,
};

/**
 * The first-of-type BONUS for a given base: +50% of the base, rounded (R3, AE2).
 * A device's FIRST-ever catch of a typecode earns this on top of the base; a
 * later catch of the same type does not. Defined ONCE and used only by the
 * canonical scorer (`DrizzleCatchStore.scoreCatch`), so the upload path and the
 * re-score job add the same bonus and can't drift. The bonus floats with the
 * base — a first-of-type epic (100) earns 50, but if re-tiered to rare (50) it
 * earns 25.
 */
export function firstOfTypeBonus(base: number): number {
  return Math.round(base * FIRST_OF_TYPE_BONUS_FRACTION);
}

/**
 * The correct-guess BONUS for a given base: +10% (route) / +25% (type) of the
 * base, rounded. Like `firstOfTypeBonus`, defined ONCE and used only by the
 * canonical scorer — the VERDICT is frozen on the row at upload, but the
 * AMOUNT floats with the re-derived base at rescore time.
 */
export function guessBonus(base: number, kind: GuessKind): number {
  return Math.round(base * GUESS_BONUS_FRACTIONS[kind]);
}
