#!/bin/bash
#
# ci_post_clone.sh — Xcode Cloud post-clone hook.
#
# Runs after Apple's CI clones the repo, before any build/test/archive
# action. We use it to materialize ios/Tailspot/Tailspot.secrets.xcconfig
# from Xcode Cloud workflow environment variables, since the real
# secrets file is gitignored and never ships in the repo.
#
# REQUIRED workflow environment variables (configure once):
#   Xcode Cloud → Manage Workflows → <workflow> → Environment →
#   Environment Variables → "+" → mark as "Secret":
#     OPENSKY_CLIENT_ID      — OAuth2 client_id from OpenSky API console
#     OPENSKY_CLIENT_SECRET  — OAuth2 client_secret from same
#
# If either variable is unset/empty, the script writes nothing and
# the build proceeds in anonymous mode (400 OpenSky credits/day,
# exhausted in ~1.3hr per IP). The build itself still succeeds.
#
# Apple's convention: the ci_scripts directory must live either at
# the repo root OR at the same directory level as the .xcodeproj.
# Ours is at the latter (ios/Tailspot/ci_scripts/) since the iOS app
# isn't at the repo root.
#
# https://developer.apple.com/documentation/xcode/writing-custom-build-scripts

set -euo pipefail

echo "ci_post_clone: starting (CI=${CI:-unset}, CI_XCODE_CLOUD=${CI_XCODE_CLOUD:-unset})"

# Resolve paths from the script's own location so we don't depend on
# CWD (Xcode Cloud sets it to the script dir, but being explicit is
# cheap insurance).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_FILE="$PROJECT_DIR/Tailspot.secrets.xcconfig"

if [ -n "${OPENSKY_CLIENT_ID:-}" ] && [ -n "${OPENSKY_CLIENT_SECRET:-}" ]; then
    # Heredoc with quoted EOF — no shell substitution INSIDE the body
    # except where we want it on `$VAR` lines. We DO want substitution
    # here since we're injecting the env-var values.
    cat > "$SECRETS_FILE" <<EOF
// Generated by ci_scripts/ci_post_clone.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
// DO NOT COMMIT — this file is gitignored. Created from Xcode Cloud
// workflow environment variables OPENSKY_CLIENT_ID + _SECRET.
OPENSKY_CLIENT_ID = $OPENSKY_CLIENT_ID
OPENSKY_CLIENT_SECRET = $OPENSKY_CLIENT_SECRET
EOF
    # Log lengths (not values) so we can confirm from the build log
    # that the script saw real strings — without leaking them.
    echo "ci_post_clone: wrote $SECRETS_FILE (lengths: id=${#OPENSKY_CLIENT_ID}, secret=${#OPENSKY_CLIENT_SECRET})"
else
    echo "ci_post_clone: OPENSKY_CLIENT_ID and/or _SECRET not set as workflow env vars; skipping secrets file. App will run in anonymous OpenSky mode (400 credits/day)."
fi

echo "ci_post_clone: done"
