#!/bin/bash
#
# ci_post_clone.sh — Xcode Cloud post-clone hook.
#
# Runs after Apple's CI clones the repo, before any build/test/archive
# action. We use it to materialize ios/Tailspot/Tailspot.secrets.xcconfig
# from Xcode Cloud workflow environment variables, since the real
# secrets file is gitignored and never ships in the repo.
#
# Workflow environment variables (configure once):
#   Xcode Cloud → Manage Workflows → <workflow> → Environment →
#   Environment Variables → "+" → mark as "Secret":
#     OPENSKY_CLIENT_ID      — OAuth2 client_id from OpenSky API console
#     OPENSKY_CLIENT_SECRET  — OAuth2 client_secret from same
#     POSTHOG_API_KEY        — PostHog project API key (phc_…) for analytics
#
# Each secret is independent — whatever is set gets written; whatever is
# absent falls back to the empty default in Tailspot.xcconfig:
#   - no OpenSky creds → anonymous mode (400 credits/day per IP)
#   - no PostHog key   → Analytics is a silent no-op. (This is exactly why
#                        only local/dev builds reported events: CI never
#                        wrote the key, so every TestFlight build shipped
#                        with analytics disabled.)
# The build itself always succeeds regardless.
#
# Apple's convention: the ci_scripts directory must live either at
# the repo root OR at the same directory level as the .xcodeproj.
# Ours is at the latter (ios/Tailspot/ci_scripts/) since the iOS app
# isn't at the repo root.
#
# https://developer.apple.com/documentation/xcode/writing-custom-build-scripts

set -euo pipefail

echo "ci_post_clone: starting (CI=${CI:-unset}, CI_XCODE_CLOUD=${CI_XCODE_CLOUD:-unset})"

# Resolve paths from the script's own location so we don't depend on
# CWD (Xcode Cloud sets it to the script dir, but being explicit is
# cheap insurance).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_FILE="$PROJECT_DIR/Tailspot.secrets.xcconfig"

HAVE_OPENSKY=0
HAVE_POSTHOG=0
[ -n "${OPENSKY_CLIENT_ID:-}" ] && [ -n "${OPENSKY_CLIENT_SECRET:-}" ] && HAVE_OPENSKY=1
[ -n "${POSTHOG_API_KEY:-}" ] && HAVE_POSTHOG=1

if [ "$HAVE_OPENSKY" = 1 ] || [ "$HAVE_POSTHOG" = 1 ]; then
    # Build the file line-by-line in the current shell ({ } not a subshell),
    # appending only the secrets that are actually set. Each `echo` with a
    # real value performs the injection we want without a heredoc.
    {
        echo "// Generated by ci_scripts/ci_post_clone.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")."
        echo "// DO NOT COMMIT — this file is gitignored. Created from Xcode Cloud"
        echo "// workflow environment variables."
        if [ "$HAVE_OPENSKY" = 1 ]; then
            echo "OPENSKY_CLIENT_ID = $OPENSKY_CLIENT_ID"
            echo "OPENSKY_CLIENT_SECRET = $OPENSKY_CLIENT_SECRET"
        fi
        if [ "$HAVE_POSTHOG" = 1 ]; then
            echo "POSTHOG_API_KEY = $POSTHOG_API_KEY"
        fi
    } > "$SECRETS_FILE"
    # Log presence (not values) so we can confirm from the build log that the
    # script saw real strings — without leaking them.
    echo "ci_post_clone: wrote $SECRETS_FILE (opensky=$HAVE_OPENSKY, posthog=$HAVE_POSTHOG)"
else
    echo "ci_post_clone: no OPENSKY_* or POSTHOG_API_KEY workflow env vars set; skipping secrets file. App runs anonymous OpenSky (400 credits/day) with analytics disabled."
fi

echo "ci_post_clone: done"
