#!/bin/bash
#
# ci_post_clone.sh — Xcode Cloud post-clone hook.
#
# Runs after Apple's CI clones the repo, before any build/test/archive
# action. We use it to materialize ios/Tailspot/Tailspot.secrets.xcconfig
# from Xcode Cloud workflow environment variables, since the real
# secrets file is gitignored and never ships in the repo.
#
# Workflow environment variables (configure once):
#   Xcode Cloud → Manage Workflows → <workflow> → Environment →
#   Environment Variables → "+" → mark as "Secret":
#     POSTHOG_API_KEY        — PostHog project API key (phc_…) for analytics
#
# This is now the only secret. (OpenSky OAuth credentials were written here
# too until the 2026-06-21 cutover removed the OpenSky source.) When the
# PostHog key is absent, Analytics is a silent no-op and the build still
# succeeds.
#
# Apple's convention: the ci_scripts directory must live either at
# the repo root OR at the same directory level as the .xcodeproj.
# Ours is at the latter (ios/Tailspot/ci_scripts/) since the iOS app
# isn't at the repo root.
#
# https://developer.apple.com/documentation/xcode/writing-custom-build-scripts

set -euo pipefail

echo "ci_post_clone: starting (CI=${CI:-unset}, CI_XCODE_CLOUD=${CI_XCODE_CLOUD:-unset})"

# Resolve paths from the script's own location so we don't depend on
# CWD (Xcode Cloud sets it to the script dir, but being explicit is
# cheap insurance).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_FILE="$PROJECT_DIR/Tailspot.secrets.xcconfig"

if [ -n "${POSTHOG_API_KEY:-}" ]; then
    # Build the file in the current shell ({ } not a subshell). The single
    # `echo` with the real value performs the injection we want.
    {
        echo "// Generated by ci_scripts/ci_post_clone.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")."
        echo "// DO NOT COMMIT — this file is gitignored. Created from Xcode Cloud"
        echo "// workflow environment variables."
        echo "POSTHOG_API_KEY = $POSTHOG_API_KEY"
    } > "$SECRETS_FILE"
    # Log presence (not the value) so we can confirm from the build log that
    # the script saw a real string — without leaking it.
    echo "ci_post_clone: wrote $SECRETS_FILE (posthog=1)"
else
    echo "ci_post_clone: no POSTHOG_API_KEY workflow env var set; skipping secrets file. Analytics disabled; ADS-B comes from api.tailspot.app regardless."
fi

echo "ci_post_clone: done"
